"""Add cascade delete

Revision ID: 2b205c6d54e0
Revises: e43199c88481
Create Date: 2026-07-26 15:26:39.721182

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b205c6d54e0'
down_revision: str | None = 'e43199c88481'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('availability_counselor_id_fkey', 'availability', type_='foreignkey')
    op.create_foreign_key(None, 'availability', 'counselor_profiles', ['counselor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('bookings_counselor_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_client_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'counselor_profiles', ['counselor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('counselor_profiles_user_id_fkey', 'counselor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'counselor_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('intake_forms_booking_id_fkey', 'intake_forms', type_='foreignkey')
    op.create_foreign_key(None, 'intake_forms', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('payments_booking_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_booking_id_fkey', 'payments', 'bookings', ['booking_id'], ['id'])
    op.drop_constraint(None, 'intake_forms', type_='foreignkey')
    op.create_foreign_key('intake_forms_booking_id_fkey', 'intake_forms', 'bookings', ['booking_id'], ['id'])
    op.drop_constraint(None, 'counselor_profiles', type_='foreignkey')
    op.create_foreign_key('counselor_profiles_user_id_fkey', 'counselor_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_client_id_fkey', 'bookings', 'users', ['client_id'], ['id'])
    op.create_foreign_key('bookings_counselor_id_fkey', 'bookings', 'counselor_profiles', ['counselor_id'], ['id'])
    op.drop_constraint(None, 'availability', type_='foreignkey')
    op.create_foreign_key('availability_counselor_id_fkey', 'availability', 'counselor_profiles', ['counselor_id'], ['id'])
    # ### end Alembic commands ###
