"""Add verification OTP to users

Revision ID: e43199c88481
Revises: 
Create Date: 2026-07-26 15:08:49.014549

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e43199c88481'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_otp_expires_at')
    op.drop_column('users', 'verification_otp')
    # ### end Alembic commands ###
