"""Add google_calendar fields to users

Revision ID: ed81853ddf72
Revises: 2b205c6d54e0
Create Date: 2026-07-26 16:07:44.943290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed81853ddf72'
down_revision: Union[str, None] = '2b205c6d54e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_calendar_connected', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_calendar_connected')
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###
